'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AlertTriangle, CheckCircle, Info } from 'lucide-react';
import { Locale, locales } from '@/lib/i18n/config';

interface FeedbackDict {
	results: {
		title: string;
		subtitle: string;
		risks: string;
		suggestions: string;
		unusual: string;
		totalAnalyzed: string;
		pages: string;
		words: string;
		documentTab: string;
		feedbackTab: string;
		risk: string;
		suggestion: string;
		unusualClause: string;
		section: string;
		downloadReport: string;
		uploadNew: string;
	};
}

interface FeedbackPageProps {
	params: Promise<{ locale: string }>;
	dictionary: FeedbackDict;
}

function FeedbackContent({ dictionary, locale }: { dictionary: FeedbackDict; locale: Locale }) {
	const [downloading, setDownloading] = useState(false);

	const handleDownload = async () => {
		setDownloading(true);

		// Create report content
		const reportContent = `CONTRACT ANALYSIS REPORT
===========================

SUMMARY
-------
Document Title: Service Agreement
Total Analyzed: 10 pages, 4,532 words

RISKS IDENTIFIED (3)
--------------------
1. Service Scope Not Sufficiently Specified
   Section 2: The scope of services is not detailed enough, which may lead to disputes about deliverables.

2. Payment Terms May Be Too Long
   Section 4: Consider reducing payment terms to 14 days for better liquidity management.

3. Liability Clause Unusual Formulation
   Section 5: The liability limitation is unusually formulated.

SUGGESTIONS (2)
---------------
1. Specify Duration More Precisely
   Section 3: Add exact dates instead of placeholder dates.

2. Consider Adding Force Majeure Clause
   Section New: Protect both parties against unforeseen events.

UNUSUAL CLAUSES (1)
-------------------
1. Liability Limitation
   Section 5: Consider specifying a fixed amount instead of a rolling 12-month period.

---
Generated by LegalEdge AI
Analysis Date: ${new Date().toLocaleDateString()}
`;

		// Create blob and trigger download
		const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'contract-analysis-report.txt';
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);

		setDownloading(false);
	};

	return (
		<div className='container mx-auto px-4 py-8'>
			<Card className='mb-8'>
				<CardHeader>
					<CardTitle className='text-2xl font-bold'>{dictionary.results.title}</CardTitle>
					<CardDescription>
						{dictionary.results.subtitle}
					</CardDescription>
				</CardHeader>
				<CardContent>
					<div className='grid gap-4 md:grid-cols-3'>
						<div className='flex items-center space-x-2'>
							<AlertTriangle className='h-5 w-5 text-yellow-500' />
							<span>3 {dictionary.results.risks}</span>
						</div>
						<div className='flex items-center space-x-2'>
							<CheckCircle className='h-5 w-5 text-green-500' />
							<span>2 {dictionary.results.suggestions}</span>
						</div>
						<div className='flex items-center space-x-2'>
							<Info className='h-5 w-5 text-blue-500' />
							<span>1 {dictionary.results.unusual}</span>
						</div>
					</div>
					<p className='mt-4 text-sm text-muted-foreground'>
						{dictionary.results.totalAnalyzed}: 10 {dictionary.results.pages}, 4,532 {dictionary.results.words}
					</p>
				</CardContent>
			</Card>

			<Tabs defaultValue='feedback' className='mb-8'>
				<TabsList className='grid w-full grid-cols-2'>
					<TabsTrigger value='document'>{dictionary.results.documentTab}</TabsTrigger>
					<TabsTrigger value='feedback'>{dictionary.results.feedbackTab}</TabsTrigger>
				</TabsList>
				<TabsContent value='document'>
					<Card>
						<CardContent className='pt-6'>
							<pre className='font-mono text-sm whitespace-pre-wrap bg-muted p-4 rounded-md'>
								{`KONTRAKT OM TJENESTEYTING

1. PARTER
Denne avtalen er inngått mellom:
[Kunde AS] (heretter kalt "Kunden")
og
[Leverandør AS] (heretter kalt "Leverandøren")

2. TJENESTENS OMFANG
<span className="bg-yellow-200">Leverandøren skal levere følgende tjenester til Kunden:
[Detaljert beskrivelse av tjenestene]
Leverandøren forplikter seg til å utføre tjenestene i henhold til bransjestandarder og god praksis.</span>

3. VARIGHET
<span className="bg-green-200">Denne avtalen trer i kraft fra [startdato] og løper til [sluttdato], med mindre den sies opp tidligere i henhold til avtalens bestemmelser.</span>

4. VEDERLAG
Kunden skal betale Leverandøren følgende for tjenestene:
[Detaljert prisoversikt]
<span className="bg-yellow-200">Betalingsbetingelser: 30 dager netto fra fakturadato.</span>

5. ANSVARSBEGRENSNING
<span className="bg-blue-200">Leverandørens totale ansvar under denne avtalen skal ikke overstige det totale beløpet betalt av Kunden for tjenestene i løpet av de siste 12 månedene før kravet oppsto.</span>

6. KONFIDENSIALITET
Begge parter forplikter seg til å behandle all informasjon mottatt fra den andre parten som strengt konfidensiell.

7. OPPSIGELSE
<span className="bg-green-200">Hver part kan si opp denne avtalen med 60 dagers skriftlig varsel.</span>

8. LOVVALG OG VERNETING
Denne avtalen er underlagt norsk lov. Eventuelle tvister skal løses ved Oslo tingrett.

Signert:

________________________                    ________________________
For [Kunde AS]                               For [Leverandør AS]
Dato:                                        Dato:`}
							</pre>
						</CardContent>
					</Card>
				</TabsContent>
				<TabsContent value='feedback'>
					<Card>
						<CardContent className='pt-6 space-y-4'>
							<div className='space-y-2'>
								<h3 className='font-semibold flex items-center'>
									<AlertTriangle className='h-5 w-5 text-yellow-500 mr-2' />
									{dictionary.results.risk} 1
								</h3>
								<p>
									Tjenestens omfang er ikke tilstrekkelig spesifisert. Dette kan
									føre til uenigheter om leveransens innhold.
								</p>
								<Badge
									variant='outline'
									className='text-yellow-500 border-yellow-500'>
									{dictionary.results.section} 2
								</Badge>
							</div>
							<div className='space-y-2'>
								<h3 className='font-semibold flex items-center'>
									<AlertTriangle className='h-5 w-5 text-yellow-500 mr-2' />
									{dictionary.results.risk} 2
								</h3>
								<p>
									Betalingsbetingelsene kan være for lange. Vurder å redusere til
									14 dager for bedre likviditetsstyring.
								</p>
								<Badge
									variant='outline'
									className='text-yellow-500 border-yellow-500'>
									{dictionary.results.section} 4
								</Badge>
							</div>
							<div className='space-y-2'>
								<h3 className='font-semibold flex items-center'>
									<CheckCircle className='h-5 w-5 text-green-500 mr-2' />
									{dictionary.results.suggestion} 1
								</h3>
								<p>
									Spesifiser varigheten mer presist, for eksempel med eksakte
									datoer.
								</p>
								<Badge
									variant='outline'
									className='text-green-500 border-green-500'>
									{dictionary.results.section} 3
								</Badge>
							</div>
							<div className='space-y-2'>
								<h3 className='font-semibold flex items-center'>
									<CheckCircle className='h-5 w-5 text-green-500 mr-2' />
									{dictionary.results.suggestion} 2
								</h3>
								<p>
									Vurder å legge til en klausul om force majeure for å beskytte
									begge parter mot uforutsette hendelser.
								</p>
								<Badge
									variant='outline'
									className='text-green-500 border-green-500'>
									{dictionary.results.section} Ny
								</Badge>
							</div>
							<div className='space-y-2'>
								<h3 className='font-semibold flex items-center'>
									<Info className='h-5 w-5 text-blue-500 mr-2' />
									{dictionary.results.unusualClause}
								</h3>
								<p>
									Ansvarsbegrensningen er uvanlig formulert. Vurder å spesifisere
									et fast beløp i stedet for en rullerende 12-måneders periode.
								</p>
								<Badge variant='outline' className='text-blue-500 border-blue-500'>
									{dictionary.results.section} 5
								</Badge>
							</div>
						</CardContent>
					</Card>
				</TabsContent>
			</Tabs>

			<div className='flex justify-center gap-4'>
				<Button variant='default' onClick={handleDownload} disabled={downloading}>
					{downloading ? '...' : dictionary.results.downloadReport}
				</Button>
				<Link href={`/${locale}/upload`}>
					<Button variant='outline'>{dictionary.results.uploadNew}</Button>
				</Link>
			</div>
		</div>
	);
}

export default async function FeedbackPage({ params }: FeedbackPageProps) {
	const resolvedParams = await params;
	const locale = resolvedParams.locale;
	const validLocale: Locale = (locales.includes(locale as Locale) ? locale : 'en') as Locale;

	// Server-side dictionary loading
	let dictionary: FeedbackDict | null = null;
	try {
		const dictModule = await import(`@/locales/${validLocale}/common.json`);
		dictionary = dictModule.default.liveAnalyser;
	} catch (error) {
		console.error('Failed to load dictionary for locale:', validLocale);
		// Fallback to English
		const fallbackModule = await import('@/locales/en/common.json');
		dictionary = fallbackModule.default.liveAnalyser;
	}

	if (!dictionary) {
		return (
			<div className='container mx-auto px-4 py-8'>
				<div className='flex justify-center items-center min-h-[400px]'>
					<div className='animate-pulse text-muted-foreground'>Loading...</div>
				</div>
			</div>
		);
	}

	return <FeedbackContent dictionary={dictionary as FeedbackDict} locale={validLocale} />;
}
